#!/bin/bash

# includes
. `dirname $0`/common.inc

############################################################################
echo "${style_blue}${style_bold}Remove vscode flutter extension.${style_normal}"
code --uninstall-extension Dart-Code.flutter || true
echo

############################################################################
echo "${style_blue}${style_bold}Remove snapd.${style_normal}"
sudo dnf -y remove snapd
echo

############################################################################
echo "${style_blue}${style_bold}Remove all snap files.${style_normal}"
rm -rf ~/.dartServer
rm -f ~/.flutter
rm -rf ~/snap
rm -rf ~/.android
rm -rf ~/.dart-tool
sudo rm -rf /snap
sudo rm -rf /snap
sudo rm -rf /var/lib/snapd
sudo rm -rf /var/snapd
echo "Done"
echo

############################################################################
echo "${style_blue}${style_bold}Remove dart pub cache.${style_normal}"
rm -rf ~/.pub-cache
echo

############################################################################
echo "${style_blue}${style_bold}Remove android studio downloaded files.${style_normal}"
rm -rf ~/Android*
echo


