#!/bin/bash

# set terminal styles
if [ -t 1 ] ; then # are we on terminal?
    # tput available?
    if [ ! "x`which tput 2>/dev/null`" = "x" ] ; then
        # supports colors ?
        ncolors=`tput colors`
        if [ -n "$ncolors" -a  $ncolors -ge 8 ] ; then
            style_bold="`tput bold`"
            style_underline="`tput smul`"
            style_standout="`tput smso`"
            style_normal="`tput sgr0`"
            style_black="`tput setaf 0`"
            style_red="`tput setaf 1`"
            style_green="`tput setaf 2`"
            style_yellow="`tput setaf 3`"
            style_blue="`tput setaf 4`"
            style_magenta="`tput setaf 5`"
            style_cyan="`tput setaf 6`"
            style_white="`tput setaf 7`"
        fi
    fi
fi

CURRUSER=`id -u`
if [ $CURRUSER = "0" ]; then
    echo "${style_red}Do not run this script as root - you will be asked for sudo pawword!${style_normal}"
    exit
fi

# exit when any command fails
set -e

REPO_PATH=`dirname $0`

echo "${style_yellow}Enter sudo password:${style_normal}"
sudo echo

############################################################################
echo "${style_blue}${style_bold}Remove vscode flutter extension.${style_normal}"
code --uninstall-extension Dart-Code.flutter || true
echo

############################################################################
echo "${style_blue}${style_bold}Remove snapd.${style_normal}"
sudo dnf -y remove snapd
echo

############################################################################
echo "${style_blue}${style_bold}Remove all snap files.${style_normal}"
rm -rf ~/snap
rm -rf ~/.android
rm -rf ~/.dart-tool
sudo rm -rf /snap
sudo rm -rf /snap
sudo rm -rf /var/lib/snapd
sudo rm -rf /var/snapd
echo "Done"
echo

############################################################################
echo "${style_blue}${style_bold}Remove dart pub cache.${style_normal}"
rm -rf ~/.pub-cache
echo

############################################################################
echo "${style_blue}${style_bold}Remove android studio downloaded files.${style_normal}"
rm -rf ~/Android*
echo


############################################################################
echo
echo
echo "${style_yellow}${style_bold}Log off - HIGLY RECCOMENDED !!!!!${style_normal}"
xfce4-session-logout
echo

