#!/bin/bash

# includes
. `dirname $0`/includes/common.inc


############################################################################
echo "${style_blue}${style_bold}Install repo for old jdks...${style_normal}"
sudo `dirname $0`/external-repos/add-adoptium-repo
echo

############################################################################
echo "${style_blue}${style_bold}Install necessary dev-tools...${style_normal}"
sudo dnf -y install \
    git-lfs \
    python-pytest \
    python-dotenv \
    socat \
    temurin-8-jdk \
    ant \
    maven \
    zsh
echo

############################################################################
echo "${style_blue}${style_bold}Make temurin-8-jdk javac default...${style_normal}"
sudo alternatives --set javac /usr/lib/jvm/temurin-8-jdk/bin/javac
echo

############################################################################
echo "${style_yellow}${style_bold}Finished successfully!${style_normal}"
