#!/bin/bash

# includes
. `dirname $0`/includes/common.inc

############################################################################
echo "${style_blue}${style_bold}Adjust xfce4-terminal settings.${style_normal}"
mkdir -p ${HOME}/.config/xfce4/terminal
cp "${REPO_PATH}/xfce4-terminal/terminalrc" ${HOME}/.config/xfce4/terminal
echo "Done"
echo

if [ ! -e ${HOME}/.ssh/id_rsa.pub ]; then
    echo "Setup ssh key - ${style_yellow}Answer ssh-keygen's questions:${style_normal}"
    ssh-keygen -f ${HOME}/.ssh/id_rsa
    echo
fi

############################################################################
echo "${style_blue}${style_bold}Install classic-light schemes (gtksourceview).${style_normal}"
sudo cp "${REPO_PATH}/gtksourceview-classic-light/classic-light.xml" /usr/share/gtksourceview-4/styles/
echo "Done"
echo


############################################################################
echo "${style_blue}${style_bold}Update packages...${style_normal}"
sudo dnf -y update
echo

############################################################################
# RPM fusion - see https://docs.fedoraproject.org/en-US/quick-docs/rpmfusion-setup/
sudo dnf -y install \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

sudo dnf -y install \
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

############################################################################
# see https://docs.fedoraproject.org/en-US/quick-docs/installing-chromium-or-google-chrome-browsers/
echo "${style_blue}${style_bold}Prepare Google Chrome.${style_normal}"
sudo dnf -y install fedora-workstation-repositories
# with Fedora 41 syntax to enable group(repo) changed:
fedora_version=$(cat /etc/os-release | grep 'VERSION_ID=' | cut -d'=' -f2)
if [ "$fedora_version" -ge 41 ]; then
    sudo dnf -y config-manager setopt google-chrome.enabled=1
else
    sudo dnf -y config-manager --set-enabled google-chrome
fi

echo "Done"
echo

############################################################################
echo "${style_blue}${style_bold}Remove parole - it does not work well and we have VLC${style_normal}"
sudo dnf -y remove parole || true

############################################################################
echo "${style_blue}${style_bold}Install dev packages...${style_normal}"
sudo dnf -y install \
    caja \
    pluma \
    gnome-system-monitor \
    xfce4-sensors-plugin \
    xfce4-cpugraph-plugin \
    xfce4-cpufreq-plugin \
    htop \
    avahi-devel \
    avahi-tools \
    blueman \
    gedit \
    evince \
    file-roller \
    libreoffice \
    google-chrome-stable \
    firefox \
    gvfs-smb \
    vlc libavcodec-freeworld \
    \
    qt-creator \
    valgrind \
    perf \
    podman \
    podman-docker \
    clang-tools-extra \
    cmake git clazy \
    systemd-devel \
    openssl-devel \
    python3-devel python3-numpy python3-passlib python3-bcrypt \
    xsd xerces-c-devel \
    fftw-devel \
    python3-jsonschema \
    qt5-linguist qt5-doctools qt5-qtscript \
    qt5-qtlocation-devel \
    qt5-qtcharts-devel \
    qt5-qtdeclarative-devel \
    qt5-qtlocation-devel \
    qt5-qtmultimedia-devel \
    qt5-qtquickcontrols qt5-qtquickcontrols2-devel \
    qt5-qtsensors-devel \
    qt5-qtserialport-devel \
    qt5-qtsvg-devel \
    qt5-qttools-devel \
    qt5-qtvirtualkeyboard-devel \
    qt5-qtwayland-devel \
    qt5-qtwebchannel-devel \
    qt5-qtwebengine-devel \
    qt5-qtwebkit-devel \
    qt5-qtx11extras-devel \
    qt5-qtxmlpatterns-devel \
    qt5-qtconnectivity-devel \
    qt-devel \
    kf5-networkmanager-qt-devel kf5-modemmanager-qt-devel kf5-syntax-highlighting-devel \
    qwt-qt5-devel \
    \
    flatbuffers-devel flatbuffers-compiler protobuf-devel protobuf-compiler \
    jq \
    xz \
    ninja-build \
    ansible \
    npm \
    java \
    xmlstarlet \
    python3-pylint \
    python3-pytest \
    python3-lsp-server \
    python3-flask \
    \
    gtest-devel \
    cpputest-devel \
    lcov gcovr \
    kernel-devel \
    glmark2 \
    sqlitebrowser \
    plantuml plantumlqeditor \
    dialog \
    ghex \
    gnuplot \
    kolourpaint \
    krdc \
    kcachegrind \
    cppcheck \
    wireshark nmap \
    nuget \
    nunit \
    minicom \
    putty telnet \
    ncurses-compat-libs \
    libusb-compat-0.1 \
    GConf2 \
    glibc.i686

sudo sudo dnf -y remove bash-color-prompt || true

# ncurses-compat-libs for TI-DSP see https://www.ti.com/tool/CCSTUDIO
echo

############################################################################
echo "${style_blue}${style_bold}Add to group dialout.${style_normal}"
ME=$(whoami)
sudo usermod -aG dialout "$ME"
echo "Done"
echo

############################################################################
echo "${style_blue}${style_bold}Quieten docker / podman notes.${style_normal}"
sudo touch /etc/containers/nodocker
echo "Done"
echo

############################################################################
echo
echo
echo "${style_yellow}${style_bold}Log off - HIGLY RECOMMENDED !!!!!${style_normal}"
xfce4-session-logout
echo
