#!/bin/sh

# exit when any command fails
set -e

# set terminal styles
if [ -t 1 ] ; then # are we on terminal?
    # tput available?
    if [ ! "x`which tput 2>/dev/null`" = "x" ] ; then
        # supports colors ?
        ncolors=`tput colors`
        if [ -n "$ncolors" -a  $ncolors -ge 8 ] ; then
            style_bold="`tput bold`"
            style_underline="`tput smul`"
            style_standout="`tput smso`"
            style_normal="`tput sgr0`"
            style_black="`tput setaf 0`"
            style_red="`tput setaf 1`"
            style_green="`tput setaf 2`"
            style_yellow="`tput setaf 3`"
            style_blue="`tput setaf 4`"
            style_magenta="`tput setaf 5`"
            style_cyan="`tput setaf 6`"
            style_white="`tput setaf 7`"
        fi
    fi
fi

REPO_PATH=`dirname $0`

echo "Adjust xfce4-terminal."
mkdir -p ${HOME}/.config/xfce4/terminal
cp "${REPO_PATH}/xfce4-terminal/terminalrc" ${HOME}/.config/xfce4/terminal
echo

if [ ! -e ${HOME}/.ssh/id_rsa.pub ]; then
    echo "Setup ssh key - ${style_yellow}Answer ssh-keygen's questions:${style_normal}"
    ssh-keygen
    echo
fi

echo "${style_yellow}Enter sudo password:${style_normal}"
sudo echo

echo "${style_green}Update packages...${style_normal}"
sudo dnf update

echo "${style_green}Install dev packages...${style_normal}"
sudo dnf install \
    caja \
    pluma \
    gnome-system-monitor \
    xfce4-sensors-plugin \
    xfce4-cpugraph-plugin \
    xfce4-cpufreq-plugin \
    htop \
    gedit \
    libreoffice \
    \
    qt-creator \
    podman \
    podman-docker \
    clang-tools-extra \
    cmake git clazy \
    systemd-devel \
    openssl-devel \
    python3-devel python3-numpy \
    xsd xerces-c-devel \
    fftw-devel \
    php-jsonlint python3-jsonschema \
    qt5-linguist qt5-doctools qt5-qtscript \
    qt5-qtlocation-devel \
    qt5-qtcharts-devel \
    qt5-qtdeclarative-devel \
    qt5-qtlocation-devel \
    qt5-qtmultimedia-devel \
    qt5-qtquickcontrols2-devel \
    qt5-qtsensors-devel \
    qt5-qtserialport-devel \
    qt5-qtsvg-devel \
    qt5-qttools-devel \
    qt5-qtvirtualkeyboard-devel \
    qt5-qtwayland-devel \
    qt5-qtwebchannel-devel \
    qt5-qtwebengine-devel \
    qt5-qtwebkit-devel \
    qt5-qtx11extras-devel \
    qt5-qtxmlpatterns-devel \
    qt-devel \
    \
    kf5-networkmanager-qt-devel kf5-modemmanager-qt-devel kf5-syntax-highlighting-devel \
    \
    qwt-qt5-devel \
    \
    flatbuffers-devel flatbuffers-compiler protobuf-devel protobuf-compiler \
    \
    gtest-devel \
    plantuml plantumlqeditor

# Quieten docker / podman notes:
sudo touch /etc/containers/nodocker

echo "${style_green}Install classic-light schemes (gtksourceview)...${style_normal}"
sudo cp "${REPO_PATH}/gtksourceview-classic-light/classic-light.xml" /usr/share/gtksourceview-4/styles/

echo
echo "${style_blue}Maybe log off / log on is a good thing to do now???${style_normal}"

