#!/bin/bash

# includes
. `dirname $0`/includes/common.inc
. `dirname $0`/includes/snap.inc
. `dirname $0`/includes/vscode.inc

############################################################################
echo "${style_blue}${style_bold}Install Android Studio (SDK is loaded on first start).${style_normal}"
sudo snap install android-studio --classic
echo

############################################################################
# https://docs.flutter.dev/get-started/install/linux
echo "${style_blue}${style_bold}Install Flutter - may take a while.${style_normal}"
sudo snap install flutter --classic
# Something in here installs ${HOME}/snap...
flutter upgrade
flutter sdk-path
flutter config --no-analytics
flutter --disable-analytics
flutter config --android-sdk ~/Android/Sdk
flutter doctor
echo

############################################################################
install_bare_vscode

echo "${style_blue}${style_bold}Install VSCode Flutter extension.${style_normal}"
code --install-extension Dart-Code.flutter
echo

