#!/bin/bash

# includes
. `dirname $0`/common.inc

############################################################################
# see https://www.virtualbox.org/wiki/Linux_Downloads
if [ ! -e /etc/yum.repos.d/virtualbox.repo ]; then
    echo "${style_blue}${style_bold}Prepare VirtualBox.${style_normal}"
    sudo rpm --import https://www.virtualbox.org/download/oracle_vbox_2016.asc
    pushd /etc/yum.repos.d/
    sudo wget https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    popd > /dev/null
    echo
fi

############################################################################
echo "${style_blue}${style_bold}Install VirtualBox...${style_normal}"
sudo dnf -y install \
    VirtualBox-7.0

