#!/bin/bash

# includes
. `dirname $0`/includes/common.inc
. `dirname $0`/includes/vscode.inc

############################################################################
echo "${style_blue}${style_bold}Install arm-none-eabi-gdb aka gdb-multiarch...${style_normal}"
sudo dnf -y install dnf-plugins-core
sudo dnf -y copr enable rleh/arm-none-eabi-gdb
sudo dnf -y install arm-none-eabi-gdb

sudo dnf -y install arm-none-eabi-binutils*
sudo ln -sf /usr/bin/arm-none-eabi-gdb /usr/bin/gdb-multiarch
sudo ln -sf /usr/bin/arm-none-eabi-objdump /usr/bin/objdump-multiarch
sudo ln -sf /usr/bin/arm-none-eabi-nm /usr/bin/nm-multiarch

sudo dnf -y install hidapi
echo

############################################################################
echo "${style_blue}${style_bold}Install Raspberry Pi Pico udev-rules...${style_normal}"
sudo cp `dirname $0`/udev-rules/99-pico.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules
echo

############################################################################
install_bare_vscode

echo "${style_blue}${style_bold}Install Raspberry Pi Pico VSCode extension...${style_normal}"
code --install-extension raspberry-pi.raspberry-pi-pico
echo

for file in `find "$HOME/.vscode" -name 'pico_project.py'`; do
    sed -i 's|${{command:raspberry-pi-pico.getGDBPath}}|/usr/bin/gdb-multiarch|g' "$file"
done

