#!/bin/bash

# includes
. `dirname $0`/common.inc
. `dirname $0`/vscode.inc

############################################################################
echo "${style_blue}${style_bold}Install arm-none-eabi-gdb aka gdb-multiarch...${style_normal}"
sudo dnf -y install dnf-plugins-core
sudo dnf -y copr enable rleh/arm-none-eabi-gdb
sudo dnf -y install arm-none-eabi-gdb
if ! grep -i -q 'alias gdb-multiarch' ${HOME}/.bashrc; then
    echo "${style_blue}${style_bold}Create gdb-multiarch alias...${style_normal}"
    echo >> ${HOME}/.bashrc
    echo 'alias gdb-multiarch=arm-none-eabi-gdb' >> ${HOME}/.bashrc
fi
echo

############################################################################
echo "${style_blue}${style_bold}Install Raspberry Pi Pico udev-rules...${style_normal}"
sudo cp `dirname $0`/udev-rules/99-pico.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules
echo

############################################################################
install_bare_vscode

echo "${style_blue}${style_bold}Install Raspberry Pi Pico VSCode extension...${style_normal}"
code --install-extension raspberry-pi.raspberry-pi-pico
echo


