#!/bin/bash

# includes
. `dirname $0`/common.inc

############################################################################
echo "${style_blue}${style_bold}Install angular.${style_normal}"
sudo npm install -g @angular/cli
echo

############################################################################
echo "${style_blue}${style_bold}Install newman/postman.${style_normal}"
sudo npm install -g newman postman
echo

############################################################################
if [ ! -e /snap ]; then
    echo "${style_blue}${style_bold}Make sure, snapd supports --classic.${style_normal}"
    sudo ln -sf /var/lib/snapd/snap /snap
    echo "Done"
fi

echo "${style_blue}${style_bold}Make sure, snapd is started/ready for operation.${style_normal}"
sudo systemctl start snapd.seeded.service
echo "Done"
echo

echo "${style_blue}${style_bold}Force snapd environment on first install of snapd.${style_normal}"
# This is what /etc/bashrc does
. /etc/profile.d/snapd.sh
echo "Done"
echo

echo "${style_blue}${style_bold}Check for snapd in PATH.${style_normal}"
SNAP_ENV_FOUND=0
echo "$PATH" | grep -q 'snapd' && SNAP_ENV_FOUND=1
if [ "$SNAP_ENV_FOUND" = "1" ]; then
    echo "OK"
else
    echo "${style_red}${style_bold}The environment for snap was not (yet) set."
    echo "Log off (or better restart) and run this script again to install snaps.${style_normal}"
    exit
fi
echo

echo "${style_blue}${style_bold}Refreshing snap.${style_normal}"
sudo snap refresh
echo

############################################################################
echo "${style_blue}${style_bold}Install Android Studio (SDK is loaded on first start).${style_normal}"
sudo snap install android-studio --classic
echo

############################################################################
# https://docs.flutter.dev/get-started/install/linux
echo "${style_blue}${style_bold}Install Flutter - may take a while.${style_normal}"
sudo snap install flutter --classic
# Something in here installs ${HOME}/snap...
flutter upgrade
flutter sdk-path
flutter config --no-analytics
flutter --disable-analytics
flutter config --android-sdk ~/Android/Sdk
flutter doctor
echo

echo "${style_blue}${style_bold}Install VSCode Flutter extension.${style_normal}"
code --install-extension Dart-Code.flutter
echo


# Kill sudo passwort-timeout prevention
kill -9 $sudo_pid


############################################################################
echo
echo
echo "${style_yellow}${style_bold}Log off - HIGLY RECOMMENDED !!!!!${style_normal}"
xfce4-session-logout
echo
