#!/bin/bash

# includes
. `dirname $0`/common.inc

############################################################################
# see https://code.visualstudio.com/docs/setup/linux
if [ ! -e /etc/yum.repos.d/vscode.repo ]; then
    echo "${style_blue}${style_bold}Prepare VSCode.${style_normal}"
    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    echo
fi

############################################################################
echo "${style_blue}${style_bold}Install code package...${style_normal}"
sudo dnf -y install \
    code \

############################################################################
echo "${style_blue}${style_bold}Install VSCode C++/CMake extensions.${style_normal}"
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cmake-tools
echo

echo "${style_blue}${style_bold}Install VSCode Python support.${style_normal}"
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension VisualStudioExptTeam.vscodeintellicode
echo

echo "${style_blue}${style_bold}Install VSCode .NET/C# related extensions.${style_normal}"
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.csdevkit
code --install-extension patcx.vscode-nuget-gallery
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension EditorConfig.EditorConfig
code --install-extension formulahendry.dotnet-test-explorer
echo

echo "${style_blue}${style_bold}Install VSCode useful extensions.${style_normal}"
code --install-extension ms-vscode.hexeditor
code --install-extension ms-azuretools.vscode-docker
code --install-extension bierner.markdown-preview-github-styles
code --install-extension GitHub.vscode-github-actions
code --install-extension  ms-vscode-remote.vscode-remote-extensionpack
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.auto-close-tag
code --install-extension mohsen1.prettify-json
code --install-extension jebbs.plantuml
code --install-extension streetsidesoftware.code-spell-checker
echo

# Kill sudo passwort-timeout prevention
kill -9 $sudo_pid


############################################################################
echo
echo
echo "${style_yellow}${style_bold}Finished successfully!${style_normal}"
