#!/bin/bash

# includes
. `dirname $0`/includes/common.inc
. `dirname $0`/includes/vscode.inc

install_bare_vscode

############################################################################
echo "${style_blue}${style_bold}Install VSCode C++/CMake extensions.${style_normal}"
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cmake-tools
echo

echo "${style_blue}${style_bold}Install VSCode Python support.${style_normal}"
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension VisualStudioExptTeam.vscodeintellicode
echo

echo "${style_blue}${style_bold}Install VSCode useful extensions.${style_normal}"
code --install-extension ms-vscode.hexeditor
code --install-extension ms-azuretools.vscode-docker
code --install-extension bierner.markdown-preview-github-styles
code --install-extension GitHub.vscode-github-actions
code --install-extension  ms-vscode-remote.vscode-remote-extensionpack
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.auto-close-tag
code --install-extension mohsen1.prettify-json
code --install-extension jebbs.plantuml
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension ritwickdey.liveserver
echo

############################################################################
echo
echo "${style_yellow}${style_bold}Finished successfully!${style_normal}"
